name: 'compile-badges-action'
description: '⚙️Save all your README badges as SVGs to save bandwidth'
author: 'Noah Koontz'
inputs:
  input_markdown_file:
    required: false
    description: The file to load and parse for badges to replace
    default: README.md
  output_markdown_file:
    required: false
    description: The file to write when parsing and replacing is complete
    default: README.md
  output_image_dir:
    required: false
    description: |
      The directory to write all the fetched badge SVGs to. This path must
      be relative and contained in the current repository.
    default: readme
  current_repository:
    required: false
    description: |
      The current repository in owner/name format. This value is used to
      generate URLs to raw.githack.com from a relative path in
      the repository. It is recommended this be left as the default value.
    default: ${{ github.repository }}
  current_branch:
    required: false
    description: |
      The current branch/ref in github.ref format. This value is used to
      generate URLs to raw.githack.com from a relative path in
      the repository. It is recommended this be left as the default value.
    default: ${{ github.ref }}
  cdn:
    required: false
    description: |
      Use githack's CloudFlare CDN for caching of provided badges.
      This might cause delays and changes are not immediately visible.
      The generated URLs will contain rawcdn.githack.com as source domain.
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: green
  icon: archive
